### ISSUE TITLE
聊天记录多的了以后会出现请求超时

### ISSUE THREAD

**Issue by vangogogo** [zhengbangbo/chat-simplifier#13]
一旦微信聊天记录大于一定数量（比如：>=200条），请求会超时。

**Comment by zhengbangbo** [comment]
<details>
<summary>之前的错误理解</summary>

本项目设置的最大 Token 数是 2000[^1]，200条聊天记录大概率超过了这个数值。Token 数可以使用 [tokenizer](https://platform.openai.com/tokenizer) 计算。

如果需要，可以自己部署网站，然后把项目中的 `max_tokens` 调到最大值 4096[^2]。

[^1]: https://github.com/zhengbangbo/chat-simplifier/blob/6dc512c6b4064e83c7230deb3daaa01d428812db/pages/api/generate.ts#L31
[^2]: https://platform.openai.com/docs/api-reference/chat/create#chat/create-max_tokens

</details>

尴尬，原来 `max_token` 是指的生成内容（`completion `）的最大长度。
