### ISSUE TITLE
请问一分钟只能请求三次吗？

### ISSUE THREAD

**Issue by dowebai** [zhengbangbo/chat-simplifier#17]
这个是openai官方限制吗？但是我同一个apikey，用其它的聊天类的chatgpt开源项目，好像都没有次数限制

**Comment by zhengbangbo** [comment]
据我所知是最近的修改，如果你的 OpenAI 帐号没有绑卡的话，会被限制到每分钟三次。具体细节可以查看官方文档。

这个和用什么开源项目没有关系，都会有这个限制的。

**Comment by dowebai** [comment]
那请问可以多添加几个apikey吗？用不了就读取下一个

**Comment by zhengbangbo** [comment]
> 那请问可以多添加几个apikey吗？用不了就读取下一个

目前是可以设置多个 key 的，用逗号分隔。
不过现在只是简单得从其中随机选择。

**Comment by dowebai** [comment]
好的，谢谢，为啥我搭建的那种对话聊天的ChatGPT网站，可以不限制的一直聊下去，也是同样免费的账户

**Comment by zhengbangbo** [comment]
1. https://github.com/ddiu8081/chatgpt-demo
<img width="669" alt="image" src="https://github.com/zhengbangbo/chat-simplifier/assets/18254135/6190c219-a2c2-4017-9708-94e0d1cc7e7d">

2. https://github.com/Yidadaa/ChatGPT-Next-Web
<img width="1087" alt="image" src="https://github.com/zhengbangbo/chat-simplifier/assets/18254135/e65d99d7-3aad-4b28-b679-1a56f6fe36a8">

3. https://bobtranslate.com/
<img width="415" alt="image" src="https://github.com/zhengbangbo/chat-simplifier/assets/18254135/f15a9f6f-125b-4b41-b9a2-1ba75834fcc7">

4. https://chatgpt-sidebar.com/
<img width="379" alt="image" src="https://github.com/zhengbangbo/chat-simplifier/assets/18254135/88e2dae2-a10e-4e2e-82ed-4bb782906f55">

我随意测试了四个应用，免费账户都会被限制。绑卡账户就不会。

**Comment by dowebai** [comment]
好的，谢谢啦，大佬有没有考虑添加会员功能呢

**Comment by zhengbangbo** [comment]
这个项目[有天生缺陷](https://github.com/zhengbangbo/chat-simplifier/issues/8)，使用起来不太方便，所以我目前没有打算继续发展。

如果你想加，可以自己开发会员功能。
