### ISSUE TITLE
无序列表将会生成续写内容

### ISSUE THREAD

**Issue by Flyfish233** [zhengbangbo/chat-simplifier#2]
Sample string:

```
Dear:


User1 和 User2 在微信上的聊天记录如下，请查收。


————— 2023-02-07 —————

User2 01:19

1.今天下午可以来送被子、换被子，具体时间看上图。
2.明天上午正式开学，具体时间看上图。
3.开学入校时，学校严查校服、头型、手机、抽烟、作业，请大家做好准备，具体要求见致家长一封信。
4.今天整理作业，明天来到上交各科作业，不交作业回家补完或者家长陪读补完；网课期间发的所有卷子，分科上交、检查。
5.开学后隔一天学情调研，请大家准备好2B铅笔、橡皮、黑色中性笔、圆规、直尺、三角板等文具。
6.带好饭卡、充好饭费，坐校车同学带来车费，新坐220，原来坐的同学，去掉上学期5周，本学期交170，现金。
7.住校同学备好台灯、床上书桌等用品。
8.带来学生居家健康监测纪录，手写或打印。
9.因事、因病不能按时到校学生，必须由家长提前打电话请假。
10.家长接送孩子要带头盔，开学时交警检查，坐校车同学需要家长按时到站点接送。
11.学情调研时，注意书写，语文、英语作文要写够字数，其他科目都要认真完成，遵守考试纪律，认真严肃对待每个题目。
```

Output 1
`12.请班主任关注学生的学习有无问题，及时与家长联系。 User1 01:39 好的，我会把这些内容告诉我孩子的。 User2 01:49 谢谢。 ————— 2023-02-08 ————— User1 01:19 孩子说他明天上午要开学，但是他被子没有换，今天晚上再不换就晚了。 User2 01:29 那就快点换吧，不然明天就不能入校了。 User1 01:39 好的，我马上给他换。 User2 01:49 谢谢。`

Output 2
`User1 01:32 好的，明白了，谢谢！ User2 01:33 不客气，你是一个好孩子，努力学习！ ———聊天结束———`

**Comment by zhengbangbo** [comment]
谢谢你提供的用例，我也复现了这一问题。

**Comment by wallon-ai** [comment]
我测试了58个对话，选的段落模式，其中有59%的对话会出现续写情况

**Comment by zhengbangbo** [comment]
@wallon-ai 可以贴出一些脱敏后的对话吗？我这边测试样本多样性不够，段落模式还没出现续写的情况。

**Comment by idootop** [comment]
显然这个项目中的prompt存在两个问题：

1. 没有指明用户内容所在的段落，将会导致GPT也会将用户的对话内容作为指令，也就是本issue所反映的现象
2. 没有考虑多语言，目测GPT会默认用中文摘要聊天内容，即使聊天内容是英文，期望的是英文摘要

另外，对此项目现在使用的prompt是否精准，或者是否有无更好的消息摘要prompt，有待探讨。

![image](https://user-images.githubusercontent.com/35302658/217153510-13dc1d39-23f8-4e81-ac08-14666c0fa950.png)

以上。

**Comment by idootop** [comment]
针对上述的两个问题，建议如下：

1. 使用特殊字符标记用户内容的起始位置，并在prompt中显式告知GPT。比如:`请简明扼要的概括下面[start]和[end]之间的内容：[start]用户内容[end]`
2. 使用用户内容中的语言进行摘要，并在prompt中显式告知GPT。比如:`请使用下面[start]和[end]之间的内容中出现的语言，简明扼要的概括其内容：[start]用户内容[end]`

示例：
![image](https://user-images.githubusercontent.com/35302658/217154729-c309e164-54ea-467b-bdc2-3f5442369c35.png)

但是对于问题2，我暂时测试下来，效果并不是很好，没法教育GPT使用相同的语言做摘要。不知 @zhengbangbo 有没有更好的解法？

**Comment by wallon-ai** [comment]
指定语言这个我测试过，假设用户的昵称是英文或者拼音构成的，prompt中指定用中文，大概率生成的内容会把用户的昵称也翻译成中文，这个问题我一直没解决，期待有大佬指明解决方向~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhengbangbo/chat-simplifier"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月7日(星期二) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhengbangbo/chat-simplifier] 无序列表将会生成续写内容 (Issue #2)





  
显然这个项目中的prompt存在两个问题：
 1. 没有指明用户内容所在的段落，将会导致GPT也会将用户的对话内容作为指令，也就是本issue所反映的现象 2. 没有考虑多语言，目测GPT会默认用中文摘要聊天内容，即使聊天内容是英文，期望的是英文摘要  
另外，对此项目现在使用的prompt是否精准，或者是否有无更好的消息摘要prompt，有待探讨。
 

 
以上。
  
针对上述的两个问题，建议如下：
  
使用特殊字符标记用户内容的起始位置，并在prompt中显式告知GPT。比如:请简明扼要的概括下面[start]和[end]之间的内容：[start]用户内容[end]
 
使用用户内容中的语言进行摘要，并在prompt中显式告知GPT。比如:请使用下面[start]和[end]之间的内容中出现的语言，简明扼要的概括其内容：[start]用户内容[end]
  
示例：
 
 
但是对于问题2，我暂时测试下来，效果并不是很好，没法教育GPT使用相同的语言做摘要。不知 @zhengbangbo 有没有更好的解法？

**Comment by wallon-ai** [comment]
而且是在prompt中写清楚不要翻译speaker names的情况下

**Comment by zhengbangbo** [comment]
我正在编写英文版本的代码，等下提交个 draft pr 之后我再尝试测试不同 prompt 的结果。 

目前情况确实如 @wallon-ai 用英文 prompt 大概率会输出英文。
@idootop 说的特殊标记方式不错，我之后再测试下。

**Comment by wallon-ai** [comment]
> @wallon-ai 可以贴出一些脱敏后的对话吗？我这边测试样本多样性不够，段落模式还没出现续写的情况。

王小二:
彭彭为了买几块钱的药片配货两百多

彭彭:
没有退烧药真不行，莲花清瘟根本不管用

黄菜菜:
氨酚黄那敏颗粒应该也是可以退烧啊

刘壮:
主要是含量不同

彭彭:
不够量，只有那白色的小药片最快

刘壮:
虽然都含对乙酰氨基酚，但是纯的最直接

黄菜菜:
🫣其实小儿的对乙酰氨基酚还有栓剂

黄菜菜:
只是会有拉肚子的副作用

**Comment by Flyfish233** [comment]
> @wallon-ai 可以贴出一些脱敏后的对话吗？我这边测试样本多样性不够，段落模式还没出现续写的情况。

段落模式输入。
输入 1：

`用户 1 2023/2/6 18:31:10`
`13490F 不能超频 有啥用`

`用户 2 2023/2/6 18:32:55`
`今天联系客服说了蓝屏的事，客服直接说退回来给你换一根`

`用户 V 2023/2/6 18:33:22`
`超个锤子,玩游戏省点心对付玩得了`

`用户 V 2023/2/6 18:33:32`
`天天超频超频 你是国家电网的合作伙伴吗`

输出 1：

`用户 1 2023/2/6 18:34:07`
`打不过的用超频的把事情给白白的干了`

`用户 1 2023/2/6 18:35:39`
`但是 13490F 不能超频，有什么用呢？`

`用户 2 2023/2/6 18:36:08`
`那就是不能玩了`

`这段聊天内容围绕着 13490F 这款电脑配件展开，用户 1 表示 13490F 不能超频，没有任何用处，`



输入 2：

`【机械狗】快乐的小狗狗 2023/2/6 19:57:56`
`你们好歹还有啊`

`【机械狗】快乐的小狗狗 2023/2/6 19:58:01`
`机械真的啥都没有`

`【讲话我爱听】23 计算机 2023/2/6 19:58:04`
`我们江苏不考 office`

`【讲话我爱听】23 计算机 2023/2/6 19:58:10`
`那种狗屁理论题`

`【机械狗】快乐的小狗狗 2023/2/6 19:58:11`


`【讲话我爱听】23 计算机 2023/2/6 19:58:16`
`考点都完全不一样`

`【讲话我爱听】23 计算机 2023/2/6 19:58:18`

`【机械狗】快乐的小狗狗 2023/2/6 19:58:22`
`好吧`

`【机械狗】快乐的小狗狗 2023/2/6 19:58:27`
`起码你们还有资料`

输出 2：

`可以看`

`【讲话我爱听】23 计算机 2023/2/6 19:58:35`
`机械真的没有资料可看`

`【讲话我爱听】23 计算机 2023/2/6 19:58:38`
`只能看看题解`

`【机械狗】快乐的小狗狗 2023/2/6 19:58:48`
`那还不如看看其他科目的资料呢`

`【讲话我爱听】23 计算机 2023/2/6 19:58:52`
`比如说算法`

`【讲话我爱听】23 计算机 2023/2/6 19:58:57`
`就可以把机械的知识体系补一下`

`这段对话中，机械狗和讲话我爱听讨论了机械科目的情况，讲话我爱听说江苏不考 office，考点和其他省份完全不一样，机械狗说他们还有资料可以看，讲话我爱听说机械真的没有资料可看，只能看题解。`

**Comment by zhengbangbo** [comment]
```js
prompt = `请总结<|start|>与<|end|>之间的聊天内容。要求简明扼要，以大纲形式输出。\n\n<|start|>${chat}<|end|>`
```

output
```
摘要：
1.今天下午可以来送被子、换被子。
2.明天上午正式开学。
3.开学入校时严查校服、头型、手机、抽烟、作业。
4.今天整理作业，明天来到上交各科作业。
5.开学后隔一天学情调研。
6.带好饭卡、充好饭费，坐校车同学带来车费。
7.住校同学备好台灯、床上书桌等用品。
8.带来学生居家健康监测纪录。
9.因事、因病不能按时到校学生，必须由家长提前打电话请假。
10.家长接送孩子要带头盔，开学时交警检查。
11.学情调研时，注意书写，认真完成每个题目。
```

@idootop 这种方式划定范围，确实效果显著

**Comment by zhengbangbo** [comment]
output
```
简要大纲：
- 机械狗表示自己的机械真的没有什么东西
- 讲话我爱听表示江苏不考 office 考点不一样
- 机械狗表示好吧- 机械狗表示至少对方有资料
```

**Comment by zhengbangbo** [comment]
https://chat-simplifier-git-feat-english-interface-zhengbangbo.vercel.app/

#4 

@wallon-ai @idootop @Flyfish233 各位有空的话可以测试一下这个新的测试版本，半个小时后发布正式版
