### ISSUE TITLE
兼容多语言摘要

### ISSUE THREAD

**Issue by idootop** [zhengbangbo/chat-simplifier#6]
> 看到上一个issue被关闭了，但只解决了用户对话内容范围的这个问题，还遗留了一个多语言的问题，待完善，所以新开一个issue在此讨论

目前项目没有考虑多语言的情况。举例：
1. 中文对话，期望摘要得出的内容是中文
2. 英文对话，期望得出的内容是英文
3. 英文对话，期望得出的内容翻译为中文
4. 中英文混合对话，期望得出的内容是指定中/英文的一种
5. 中英文混合对话，期望得出的内容的语言是摘要内容中最主要使用的语言

问题：现在以中文prompt去询问GPT的话，得出来的结果，目测都是中文摘要，即使所有内容都为英文。 

So sad.....

**Comment by zhengbangbo** [comment]
> 现在以中文prompt去询问GPT的话，得出来的结果，目测都是中文摘要，即使所有内容都为英文。

切换到英文界面，就是使用英文 prompt 进行询问了。

**Comment by zhengbangbo** [comment]
> 1. 中文对话，期望摘要得出的内容是中文
> 2. 英文对话，期望得出的内容是英文
> 3. 英文对话，期望得出的内容翻译为中文
> 4. 中英文混合对话，期望得出的内容是指定中/英文的一种
> 5. 中英文混合对话，期望得出的内容的语言是摘要内容中最主要使用的语言

对于前两项，目前是按照页面语言和prompt前缀所使用语言一一对应的。比如页面是英语，prompt前缀就是「Please summarize the chat content between <|start|> and <|end|>. ......」。可能现在的逻辑不够直观，让你有误会了。加个文字提示？你有什么好的改进建议吗？

对于后三项，我目前的感觉是没有必要。3. 4. 两项，如果要实现，再加语言下拉框选择就可以解决。最后一项，如果要实现，就需要用 ChatGPT 自动判断主要语言。

**Comment by zhengbangbo** [comment]
还有就是我的测试量确实比较少，可能有些中文页面输出英文结果，或者反过来的场景我没有遇到。如果大家有遇到，也是欢迎贴上脱敏的输入输出。

**Comment by idootop** [comment]
我的意思是自动检测语言，而非通过网页上的切换语言选项去控制，寻找一个通用的prompt，兼容多语言。当然这个要求跟此项目有点不相关了，只是交流探讨下。

**Comment by zhengbangbo** [comment]
> 我的意思是自动检测语言，而非通过网页上的切换语言选项去控制，寻找一个通用的prompt，兼容多语言。当然这个要求跟此项目有点不相关了，只是交流探讨下。

感觉你这有点 prompt 语言编程的意思了，哈哈。
